<?php
/*
Template Name: Custom terms-bi Page
*/
get_header('custom-bi'); 
 
 ?>
<section class="page-title-area text-white bg_cover" style="background-image: url(<?php echo get_stylesheet_directory_uri(); ?>/assets/images/gallery/5.jpg);">
            <div class="container">
                <!--======  Page-title-Inner ======-->
                <div class="page-title-inner text-center">
                    <h1 class="page-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ਸ਼ਰਤਾਂ</font></font></h1>
                    <div class="gd-breadcrumb">
                        <span class="breadcrumb-entry"><a href="/index-bi"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ਘਰ</font></font></a></span>
                        <span class="separator"></span>
                        <span class="breadcrumb-entry active"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ਸ਼ਰਤਾਂ</font></font></span>
                    </div>
                </div>
            </div>
        </section>

        <!-- start blog_wrap -->
    <section class="blog_wrap pt_90">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 cus_pad_left">
                    <div class="blog_content blog_single_content pb_100">
                        <div class="blog_single_item wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
                           
                           <p class="about_para mt-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">                          
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ, ਕਿਸਾਨਾਂ ਲਈ ਇੱਕ ਏਕੀਕ੍ਰਿਤ ਖੇਤੀਬਾੜੀ ਈਕੋਸਿਸਟਮ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਦੀ ਵਰਤੋਂ ਕਰਕੇ, ਤੁਸੀਂ ਨਿਮਨਲਿਖਤ ਨਿਯਮਾਂ ਅਤੇ ਸ਼ਰਤਾਂ ਦੁਆਰਾ ਪਾਬੰਦ ਹੋਣ ਨੂੰ ਸਵੀਕਾਰ ਕਰਦੇ ਹੋ ਅਤੇ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ। </font><font style="vertical-align: inherit;">ਇਹਨਾਂ ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ (ToS) ਵਿੱਚ ਸ਼ਾਮਲ ਕੁਝ ਵੀ ਕਿਸੇ ਤੀਜੀ ਧਿਰ ਦੇ ਲਾਭਪਾਤਰੀ ਨੂੰ ਕੋਈ ਅਧਿਕਾਰ ਦੇਣ ਲਈ ਨਹੀਂ ਸਮਝਿਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਵਿੱਚ ਬਦਲਾਅ ਅਤੇ ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਕਿਸੇ ਵੀ ਕਾਰਨ ਕਰਕੇ, ਬਿਨਾਂ ਕਿਸੇ ਅਗਾਊਂ ਨੋਟਿਸ ਦੇ, ਉਪਭੋਗਤਾ ਜਾਂ ਕਿਸੇ ਹੋਰ ਮੈਂਬਰ ਜਾਂ ਤੀਜੀ ਧਿਰ ਦੀ ਦੇਣਦਾਰੀ ਦੇ ਬਿਨਾਂ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਨੂੰ ਸੋਧਣ ਜਾਂ ਸਮਾਪਤ ਕਰਨ ਦਾ ਆਪਣਾ ਅਧਿਕਾਰ ਰਾਖਵਾਂ ਰੱਖਦਾ ਹੈ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਬਿਨਾਂ ਨੋਟਿਸ ਦੇ ਸਮੇਂ-ਸਮੇਂ 'ਤੇ ToS ਨੂੰ ਸੋਧਣ ਦਾ ਅਧਿਕਾਰ ਵੀ ਰਾਖਵਾਂ ਰੱਖਦਾ ਹੈ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਅਜਿਹੇ ਕਿਸੇ ਵੀ ਬਦਲਾਅ ਬਾਰੇ ਆਪਣੇ ਆਪ ਨੂੰ ਜਾਣੂ ਰੱਖਣ ਲਈ ਨਿਯਮਤ ਤੌਰ 'ਤੇ ToS ਦੀ ਸਮੀਖਿਆ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਯੋਗਤਾ, ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਪਹੁੰਚ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਦੀਆਂ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਦਾਨ ਕਰਨ ਦਾ ਫੈਸਲਾ ਸਾਈਟ ਦਾ ਵਿਸ਼ੇਸ਼ ਅਧਿਕਾਰ ਹੈ ਅਤੇ ਇਸ ਸਬੰਧ ਵਿੱਚ ਇਸਦਾ ਫੈਸਲਾ ਅੰਤਿਮ ਹੋਵੇਗਾ ਅਤੇ ਪ੍ਰਸਤਾਵਿਤ ਉਪਭੋਗਤਾ ਲਈ ਪਾਬੰਦ ਹੋਵੇਗਾ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਸਹਿਮਤੀ ਦਿੰਦਾ ਹੈ ਕਿ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਆਪਣੀਆਂ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ ਕਰਨ ਜਾਂ ਸੇਵਾਵਾਂ ਦੀ ਸਮਾਪਤੀ ਲਈ ਸਾਰੇ ਲੋੜੀਂਦੇ ਉਪਾਅ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਰਾਖਵਾਂ ਰੱਖਦਾ ਹੈ ਜੇਕਰ ਮੌਜੂਦਾ ਸਮਝੌਤੇ ਦੇ ਨਿਯਮਾਂ ਅਤੇ ਸ਼ਰਤਾਂ ਦੀ ਪਾਲਣਾ ਨਹੀਂ ਕੀਤੀ ਜਾਂਦੀ ਜਾਂ ਉਲੰਘਣਾ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਜਾਂ ਕਾਪੀਰਾਈਟ, ਟ੍ਰੇਡਮਾਰਕ ਦੀ ਕੋਈ ਉਲੰਘਣਾ ਹੁੰਦੀ ਹੈ। ਜਾਂ ਹੋਰ ਕੀਮਤੀ ਮਲਕੀਅਤ ਅਧਿਕਾਰ ਜਿਵੇਂ ਕਿ ਇਸ ਸਮਝੌਤੇ ਵਿੱਚ ਵਰਣਨ ਕੀਤਾ ਗਿਆ ਹੈ। </font><font style="vertical-align: inherit;">ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਕਰਨ ਲਈ, ਉਪਭੋਗਤਾ ਨੂੰ ਵਰਲਡ ਵਾਈਡ ਵੈੱਬ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ, ਜਾਂ ਤਾਂ ਸਿੱਧੇ ਜਾਂ ਉਹਨਾਂ ਡਿਵਾਈਸਾਂ ਦੁਆਰਾ ਜੋ ਵੈਬ-ਅਧਾਰਿਤ ਸਮੱਗਰੀ ਤੱਕ ਪਹੁੰਚ ਕਰਦੇ ਹਨ, ਅਤੇ ਅਜਿਹੀ ਪਹੁੰਚ ਨਾਲ ਸੰਬੰਧਿਤ ਸੇਵਾ ਫੀਸਾਂ ਦਾ ਭੁਗਤਾਨ ਕਰਦੇ ਹਨ। </font><font style="vertical-align: inherit;">ਇਸ ਤੋਂ ਇਲਾਵਾ, ਉਪਭੋਗਤਾ ਕੋਲ ਵਰਲਡ ਵਾਈਡ ਵੈੱਬ ਨਾਲ ਅਜਿਹਾ ਕੁਨੈਕਸ਼ਨ ਬਣਾਉਣ ਲਈ ਲੋੜੀਂਦੇ ਸਾਰੇ ਉਪਕਰਣ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ,</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਸਾਈਟ ਮੀਰਾ ਫਾਰਮਹਾਊਸ ਦੀ ਵਰਤੋਂ, ਜਾਂ ਸਾਈਟ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤੀ ਗਈ ਇਸ ਦੀਆਂ ਸੇਵਾਵਾਂ ਜਾਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਅਤੇ ਉਪਭੋਗਤਾ ਤੋਂ ਉਪਭੋਗਤਾ ਇੰਟਰਫੇਸ, ਇਸ ਵਿੱਚ ਮੌਜੂਦ ਜਾਣਕਾਰੀ ਅਤੇ ਸਮੱਗਰੀ ਇਸ ਸਮਝੌਤੇ ਲਈ ਉਪਭੋਗਤਾ ਦੀ ਸਹਿਮਤੀ ਨੂੰ ਦਰਸਾਉਂਦੀ ਹੈ ਅਤੇ ਬਣਦੀ ਹੈ, ਉਪਭੋਗਤਾ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਇਹਨਾਂ ਦੀ ਪਾਲਣਾ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ। ਨਿਬੰਧਨ ਅਤੇ ਸ਼ਰਤਾਂ. </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਉਪਭੋਗਤਾ ਨੂੰ ਬਿਨਾਂ ਕਿਸੇ ਅਗਾਊਂ ਸੂਚਨਾ ਜਾਂ ਕਿਸੇ ਵੀ ਜ਼ਿੰਮੇਵਾਰੀ ਦੇ ਆਪਣੀ ਸੇਵਾ ਦੇ ਸਾਰੇ ਜਾਂ ਕਿਸੇ ਵੀ ਹਿੱਸੇ ਦੀ ਵਰਤੋਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਰੱਖਦਾ ਹੈ।</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਉਪਭੋਗਤਾ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ ਕਿ ਉਹ ਜਾਣਕਾਰੀ, ਸਮੱਗਰੀ ਜਾਂ ਸਮੱਗਰੀ ਨੂੰ ਨਹੀਂ ਬਦਲੇਗਾ ਜਾਂ ਸਾਈਟ 'ਤੇ ਮੌਜੂਦ ਅਜਿਹੀ ਜਾਣਕਾਰੀ, ਸਮੱਗਰੀ ਜਾਂ ਸਮੱਗਰੀ ਦੀ ਵਰਤੋਂ ਕਿਸੇ ਵੀ ਉਦੇਸ਼ ਲਈ ਨਹੀਂ ਕਰੇਗਾ ਜੋ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਜਾਂ ਕਿਸੇ ਤੀਜੀ-ਧਿਰ ਜਾਣਕਾਰੀ ਪ੍ਰਦਾਤਾ ਦੇ ਕਾਪੀਰਾਈਟ ਦੀ ਉਲੰਘਣਾ ਕਰਦਾ ਹੈ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਤੋਂ ਪੂਰਵ ਲਿਖਤੀ ਸਹਿਮਤੀ ਪ੍ਰਾਪਤ ਕੀਤੇ ਬਿਨਾਂ ਕਿਸੇ ਵੀ ਵਰਤੋਂ ਲਈ ਕਿਸੇ ਵੀ ਤਰੀਕੇ ਨਾਲ ਸਮੱਗਰੀ ਨੂੰ ਕਾਪੀ, ਰੀਪ੍ਰੋਡਿਊਸ, ਦੁਬਾਰਾ ਪ੍ਰਕਾਸ਼ਿਤ, ਅਪਲੋਡ, ਪੋਸਟ, ਪ੍ਰਸਾਰਿਤ ਜਾਂ ਵੰਡਣ ਲਈ ਸਹਿਮਤ ਨਹੀਂ ਹੁੰਦਾ।</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਉਪਭੋਗਤਾ ਇਸ ਗੱਲ ਨਾਲ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ ਕਿ ਉਹ ਦੂਜੇ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਯੋਜਨਾ/ਪੁਆਇੰਟ/ਹੋਰ ਕੋਈ ਵੀ ਚੀਜ਼ ਸਾਂਝਾ ਕਰਨ ਲਈ ਬੇਨਤੀ ਜਾਂ ਸੱਦਾ ਨਹੀਂ ਦੇਣਗੇ ਜੋ ਉਹ ਕਮਾਉਂਦੇ ਹਨ, ਜੋ ਉਹਨਾਂ ਨੂੰ ਉਹਨਾਂ ਦੀ ਵਿਅਕਤੀਗਤ ਸਮਰੱਥਾ ਵਿੱਚ ਇਕੱਠਾ ਕਰਦੇ ਹਨ; </font><font style="vertical-align: inherit;">ਅਤੇ ਕਿਸੇ ਤੀਜੀ ਧਿਰ ਨੂੰ ਕਿਸੇ ਵੀ ਵਿਚਾਰ ਲਈ ਕ੍ਰੈਡਿਟ/ਪੁਆਇੰਟ/ਪੈਕ/ਕੋਰਸ/ਹੋਰ ਕੁਝ ਨਾ ਵੇਚਣ ਲਈ ਸਹਿਮਤ ਹੋਵੋ। </font><font style="vertical-align: inherit;">ਇਸ ਸ਼ਰਤ ਦੀ ਉਲੰਘਣਾ ਦੇ ਮਾਮਲੇ ਵਿੱਚ, ਉਪਭੋਗਤਾ ਕ੍ਰੈਡਿਟ/ਪੁਆਇੰਟ/ਕੋਰਸ/ਪੈਕ/ਹੋਰ ਕਿਸੇ ਵੀ ਚੀਜ਼ ਲਈ ਭੁਗਤਾਨ ਕਰਨ ਲਈ ਜਵਾਬਦੇਹ ਹੋਵੇਗਾ ਜੋ ਉਸਨੇ ਵੇਚਿਆ ਹੈ ਜਾਂ ਸਾਂਝਾ ਕੀਤਾ ਹੈ ਅਤੇ ਉਹਨਾਂ ਦੇ ਸਾਰੇ ਪਲਾਨ/ਪੁਆਇੰਟ/ਕੁਝ ਵੀ ਇਕੱਠਾ ਕੀਤਾ ਗਿਆ ਹੈ ਅਤੇ ਉਹਨਾਂ ਦਾ ਖਾਤਾ ਜ਼ਬਤ ਹੋਵੇਗਾ। ਖਤਮ ਕੀਤਾ ਜਾਵੇ।  </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਜੇਕਰ ਉਪਭੋਗਤਾ ਇਸ ਸਮਝੌਤੇ ਵਿੱਚ ਦੱਸੀਆਂ ਗਈਆਂ ਕਿਸੇ ਵੀ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਨਹੀਂ ਹੁੰਦਾ ਹੈ, ਤਾਂ ਉਹਨਾਂ ਨੂੰ ਆਪਣੇ ਬ੍ਰਾਊਜ਼ਰ ਰਾਹੀਂ ਸਾਈਟ ਤੋਂ ਬਾਹਰ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸੁਰੱਖਿਆ ਅਤੇ ਪਾਸਵਰਡ ਤੱਕ ਪਹੁੰਚ ਕਰੋ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਪਾਸਵਰਡ ਅਤੇ ਖਾਤੇ ਦੀ ਗੁਪਤਤਾ ਨੂੰ ਬਣਾਈ ਰੱਖਣ ਦਾ ਕੰਮ ਕਰਦਾ ਹੈ, ਅਤੇ ਉਹਨਾਂ ਦੇ ਪਾਸਵਰਡ ਜਾਂ ਖਾਤੇ ਦੇ ਅਧੀਨ ਹੋਣ ਵਾਲੀਆਂ ਸਾਰੀਆਂ ਕਾਰਵਾਈਆਂ ਅਤੇ ਭੁੱਲਾਂ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਜ਼ਿੰਮੇਵਾਰ ਹੋਵੇਗਾ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਇਸ ਸਮਝੌਤੇ ਦੇ ਨਿਯਮਾਂ ਅਤੇ ਸ਼ਰਤਾਂ ਦੀ ਪਾਲਣਾ ਕਰਨ ਵਿੱਚ ਉਪਭੋਗਤਾ ਦੀ ਅਸਫਲਤਾ ਤੋਂ ਹੋਣ ਵਾਲੇ ਕਿਸੇ ਵੀ ਨੁਕਸਾਨ ਜਾਂ ਨੁਕਸਾਨ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਨਹੀਂ ਹੋਵੇਗਾ ਅਤੇ ਨਹੀਂ ਹੋਵੇਗਾ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਨੂੰ ਹਮੇਸ਼ਾ ਯਾਦ ਰੱਖਣਾ ਚਾਹੀਦਾ ਹੈ ਕਿ ਉਹ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਤੋਂ ਪੂਰੀ ਤਰ੍ਹਾਂ ਨਾਲ ਲੌਗ ਆਫ ਕਰੋ ਜੇਕਰ ਉਹ ਕਿਸੇ ਜਨਤਕ ਸਥਾਨ ਤੋਂ ਇਸ ਤੱਕ ਪਹੁੰਚ ਕਰ ਰਹੇ ਹਨ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਆਪਣਾ ਪਾਸਵਰਡ ਅਕਸਰ ਬਦਲਣਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਇਸ ਨੂੰ ਕਿਸੇ ਅਣਪਛਾਤੀ ਚੀਜ਼ ਵਿੱਚ ਬਦਲਣਾ ਯਕੀਨੀ ਬਣਾਓ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਆਚਰਣ ਅਤੇ ਵਰਜਿਤ ਐਕਟ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮ ਹਾਊਸ ਸੇਵਾ ਸਿਰਫ਼ ਨਿੱਜੀ, ਗੈਰ-ਵਪਾਰਕ ਵਰਤੋਂ ਲਈ ਉਪਲਬਧ ਕਰਵਾਈ ਗਈ ਹੈ। </font><font style="vertical-align: inherit;">ਇੰਟਰਨੈੱਟ, ਟੈਲੀਵਿਜ਼ਨ, ਹੈਂਡਹੈਲਡ ਡਿਵਾਈਸਾਂ ਅਤੇ ਹੋਰ ਡਿਵਾਈਸਾਂ ਦੇ ਮਾਧਿਅਮ ਨਾਲ ਇਸ ਨੂੰ ਕਿਸੇ ਵੀ ਮਾਧਿਅਮ ਨਾਲ ਪ੍ਰਸਾਰਿਤ ਕਰਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ ਅਤੇ ਇਸ ਨੂੰ ਕੰਪਨੀ ਦੇ ਬੌਧਿਕ ਸੰਪੱਤੀ ਅਧਿਕਾਰਾਂ ਦੀ ਉਲੰਘਣਾ ਮੰਨਿਆ ਜਾਵੇਗਾ। </font><font style="vertical-align: inherit;">ਕੰਪਨੀ ਬਿਨਾਂ ਕਿਸੇ ਪੂਰਵ ਸੂਚਨਾ ਦੇ ਗਾਹਕੀ ਨੂੰ ਖਤਮ ਕਰਨ ਅਤੇ ਅਜਿਹੀ ਉਲੰਘਣਾ ਦੇ ਮਾਮਲੇ ਵਿੱਚ ਕੋਈ ਕਾਨੂੰਨੀ ਕਾਰਵਾਈ ਸ਼ੁਰੂ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਰਾਖਵਾਂ ਰੱਖਦੀ ਹੈ। </font><font style="vertical-align: inherit;">ਕਾਰੋਬਾਰਾਂ, ਸੰਸਥਾਵਾਂ ਜਾਂ ਹੋਰ ਕਾਨੂੰਨੀ ਸੰਸਥਾਵਾਂ ਨੂੰ ਕਿਸੇ ਵੀ ਉਦੇਸ਼ ਲਈ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾਵਾਂ ਦੀ ਵਰਤੋਂ ਕਰਨ ਤੋਂ ਸਖ਼ਤੀ ਨਾਲ ਰੋਕਿਆ ਗਿਆ ਹੈ।
</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਨੂੰ ਕਿਸੇ ਗੈਰ-ਕਾਨੂੰਨੀ ਜਾਂ ਅਣਅਧਿਕਾਰਤ ਉਦੇਸ਼ ਲਈ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਕਰਨ ਤੋਂ ਵਰਜਿਤ ਹੈ। </font><font style="vertical-align: inherit;">ਅੰਤਰਰਾਸ਼ਟਰੀ ਉਪਭੋਗਤਾ ਡੇਟਾ ਦੇ ਨਿਰਯਾਤ ਨੂੰ ਨਿਯੰਤ੍ਰਿਤ ਕਰਨ ਵਾਲੇ ਕਾਨੂੰਨਾਂ ਸਮੇਤ, ਔਨਲਾਈਨ ਆਚਰਣ ਅਤੇ ਸਵੀਕਾਰਯੋਗ ਸਮੱਗਰੀ ਸੰਬੰਧੀ ਸਾਰੇ ਸਥਾਨਕ ਨਿਯਮਾਂ ਦੀ ਪਾਲਣਾ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹੁੰਦੇ ਹਨ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਆਪਣੇ ਆਚਰਣ ਅਤੇ ਕਿਸੇ ਵੀ ਡੇਟਾ, ਟੈਕਸਟ, ਜਾਣਕਾਰੀ, ਗ੍ਰਾਫਿਕਸ, ਫੋਟੋਆਂ, ਪ੍ਰੋਫਾਈਲਾਂ, ਆਡੀਓ ਅਤੇ ਵੀਡੀਓ ਕਲਿੱਪਾਂ, ਲਿੰਕਾਂ ਅਤੇ ਹੋਰ ਸਮੱਗਰੀ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਜ਼ਿੰਮੇਵਾਰ ਹੈ ਜੋ ਉਹ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ 'ਤੇ ਜਮ੍ਹਾਂ ਕਰਦੇ ਹਨ, ਪੋਸਟ ਕਰਦੇ ਹਨ ਅਤੇ ਪ੍ਰਦਰਸ਼ਿਤ ਕਰਦੇ ਹਨ।
</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸਾਈਟ, ਆਪਣੀ ਪੂਰੀ ਮਰਜ਼ੀ ਨਾਲ, ਜਾਣਕਾਰੀ, ਸਮੱਗਰੀ ਜਾਂ ਸਮੱਗਰੀ ਨੂੰ ਹਟਾ ਸਕਦੀ ਹੈ ਜੋ ਗਲਤ, ਗਲਤ, ਗੈਰ-ਕਾਨੂੰਨੀ, ਧੋਖਾਧੜੀ, ਧਮਕੀ, ਬਦਨਾਮ, ਅਪਮਾਨਜਨਕ, ਅਸ਼ਲੀਲ ਜਾਂ ਹੋਰ ਇਤਰਾਜ਼ਯੋਗ ਹੈ, ਜਾਂ ਕਿਸੇ ਪਾਰਟੀ ਦੀ ਬੌਧਿਕ ਜਾਇਦਾਦ ਜਾਂ ਹੋਰ ਮਲਕੀਅਤ ਅਧਿਕਾਰਾਂ ਜਾਂ ਇਹਨਾਂ ਦੀ ਉਲੰਘਣਾ ਜਾਂ ਉਲੰਘਣਾ ਕਰਦੀ ਹੈ। ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ.
</font></font><br><br></p>
<h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ਗੈਰ-ਕਾਨੂੰਨੀ ਜਾਂ ਅਣਅਧਿਕਾਰਤ ਵਰਤੋਂ ਦੀਆਂ ਹੋਰ ਉਦਾਹਰਣਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹਨ, ਪਰ ਇਹਨਾਂ ਤੱਕ ਸੀਮਿਤ ਨਹੀਂ ਹਨ:</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੇ ਕਿਸੇ ਵੀ ਹਿੱਸੇ ਨੂੰ ਸੋਧਣਾ, ਅਨੁਕੂਲ ਬਣਾਉਣਾ, ਅਨੁਵਾਦ ਕਰਨਾ, ਜਾਂ ਉਲਟਾ ਇੰਜੀਨੀਅਰਿੰਗ ਕਰਨਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਵਿੱਚ ਜਾਂ ਇਸ ਵਿੱਚ ਸ਼ਾਮਲ ਕਿਸੇ ਵੀ ਕਾਪੀਰਾਈਟ, ਟ੍ਰੇਡਮਾਰਕ ਜਾਂ ਹੋਰ ਮਲਕੀਅਤ ਅਧਿਕਾਰ ਨੋਟਿਸਾਂ ਨੂੰ ਹਟਾਉਣਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੇ ਕਿਸੇ ਵੀ ਹਿੱਸੇ ਨੂੰ ਮੁੜ ਪ੍ਰਾਪਤ ਕਰਨ ਜਾਂ ਸੂਚੀਬੱਧ ਕਰਨ ਲਈ ਕਿਸੇ ਰੋਬੋਟ, ਮੱਕੜੀ, ਸਾਈਟ ਖੋਜ/ਮੁੜ ਪ੍ਰਾਪਤੀ ਐਪਲੀਕੇਸ਼ਨ, ਜਾਂ ਕਿਸੇ ਹੋਰ ਡਿਵਾਈਸ ਦੀ ਵਰਤੋਂ ਕਰਨਾ; </font><font style="vertical-align: inherit;">- ਅਣਅਧਿਕਾਰਤ ਉਦੇਸ਼ਾਂ ਲਈ ਦੂਜੇ ਉਪਭੋਗਤਾਵਾਂ (ਉਪਭੋਗਤਾ ਨਾਮ ਅਤੇ/ਜਾਂ ਈਮੇਲ ਪਤਿਆਂ ਸਮੇਤ) ਬਾਰੇ ਕੋਈ ਵੀ ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਕਰਨਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਵੈਬ ਪੇਜਾਂ ਦੇ ਕਿਸੇ ਵੀ ਹਿੱਸੇ ਨੂੰ ਰੀਫਾਰਮੈਟ ਕਰਨਾ ਜਾਂ ਫਰੇਮ ਕਰਨਾ ਜੋ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦਾ ਹਿੱਸਾ ਹਨ; </font><font style="vertical-align: inherit;">ਸਵੈਚਲਿਤ ਤਰੀਕਿਆਂ ਨਾਲ ਜਾਂ ਝੂਠੇ ਜਾਂ ਧੋਖੇਬਾਜ਼ ਬਹਾਨੇ ਹੇਠ ਉਪਭੋਗਤਾ ਖਾਤੇ ਬਣਾਉਣਾ;</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਅਣਚਾਹੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਸੰਚਾਰਾਂ ਨੂੰ ਬਣਾਉਣਾ ਜਾਂ ਪ੍ਰਸਾਰਿਤ ਕਰਨਾ ਜਿਵੇਂ ਕਿ "ਸਪੈਮ" ਜਾਂ ਦੂਜੇ ਉਪਭੋਗਤਾ ਨੂੰ ਚੇਨ ਅੱਖਰ ਜਾਂ ਹੋਰ ਉਪਯੋਗਕਰਤਾ ਦੇ ਸੇਵਾ ਦੇ ਅਨੰਦ ਵਿੱਚ ਦਖਲ ਦੇਣਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਅਜਿਹੀ ਤੀਜੀ ਧਿਰ ਦੀ ਪੂਰਵ ਲਿਖਤੀ ਸਹਿਮਤੀ ਤੋਂ ਬਿਨਾਂ ਕਿਸੇ ਤੀਜੀ ਧਿਰ ਦੀ ਜਾਣਕਾਰੀ ਜਾਂ ਸਮੱਗਰੀ ਜਮ੍ਹਾਂ ਕਰਾਉਣਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕਿਸੇ ਵੀ ਉਪਭੋਗਤਾ ਨੂੰ ਨਿਰਦੇਸ਼ਿਤ ਕਰਨਾ (ਉਦਾਹਰਨ ਲਈ, ਲਿੰਕ ਕਰਕੇ) ਕਿਸੇ ਵੀ ਤੀਜੀ ਧਿਰ ਦੀ ਕਿਸੇ ਵੀ ਜਾਣਕਾਰੀ ਜਾਂ ਸਮੱਗਰੀ ਨੂੰ ਅਜਿਹੀ ਤੀਜੀ ਧਿਰ ਦੀ ਪੂਰਵ ਲਿਖਤੀ ਸਹਿਮਤੀ ਜਾਂ ਉਪਭੋਗਤਾ ਦੀ ਸਹਿਮਤੀ ਤੋਂ ਬਿਨਾਂ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕਿਸੇ ਵੀ ਪਾਰਟੀ ਦੇ ਬੌਧਿਕ ਸੰਪੱਤੀ, ਪ੍ਰਚਾਰ, ਗੋਪਨੀਯਤਾ ਜਾਂ ਹੋਰ ਮਲਕੀਅਤ ਦੇ ਅਧਿਕਾਰਾਂ ਦੀ ਉਲੰਘਣਾ, ਦੁਰਉਪਯੋਗ ਜਾਂ ਉਲੰਘਣਾ ਕਰਨ ਵਾਲੀ ਜਾਣਕਾਰੀ ਜਾਂ ਸਮੱਗਰੀ ਨੂੰ ਜਮ੍ਹਾਂ ਕਰਨਾ;</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕਿਸੇ ਵੀ ਵਾਇਰਸ, ਕੀੜੇ, ਨੁਕਸ, ਟਰੋਜਨ ਘੋੜੇ ਜਾਂ ਵਿਨਾਸ਼ਕਾਰੀ ਕੁਦਰਤ ਦੀਆਂ ਹੋਰ ਚੀਜ਼ਾਂ ਦਾ ਸੰਚਾਰ ਕਰਨਾ; </font><font style="vertical-align: inherit;">- ਗੈਰ-ਕਾਨੂੰਨੀ ਜਾਂ ਗੈਰ-ਕਾਨੂੰਨੀ ਗਤੀਵਿਧੀ ਨੂੰ ਉਤਸ਼ਾਹਿਤ ਜਾਂ ਉਤਸ਼ਾਹਿਤ ਕਰਨ ਵਾਲੀ ਜਾਣਕਾਰੀ ਜਾਂ ਸਮੱਗਰੀ ਜਮ੍ਹਾਂ ਕਰਾਉਣਾ; </font><font style="vertical-align: inherit;">ਜਾਂ ਗਲਤ ਜਾਂ ਗੁੰਮਰਾਹਕੁੰਨ ਜਾਣਕਾਰੀ ਜਮ੍ਹਾਂ ਕਰਾਉਣਾ। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਨਾਬਾਲਗਾਂ, ਬੱਚਿਆਂ ਅਤੇ ਔਰਤਾਂ ਨੂੰ ਕਿਸੇ ਵੀ ਤਰੀਕੇ ਨਾਲ ਨੁਕਸਾਨ ਪਹੁੰਚਾਉਣਾ ਜਾਂ "ਡੰਡੇ" ਜਾਂ ਹੋਰਾਂ ਨੂੰ ਪਰੇਸ਼ਾਨ ਕਰਨਾ;</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਔਰਤਾਂ ਦੀ ਅਸ਼ਲੀਲ ਨੁਮਾਇੰਦਗੀ (ਪ੍ਰਬੰਧਨ) ਐਕਟ, 1986 ਦੇ ਅਰਥਾਂ ਵਿੱਚ ਅਸ਼ਲੀਲ, ਅਸ਼ਲੀਲ ਜਾਂ ਅਸ਼ਲੀਲ ਜਾਂ "ਔਰਤਾਂ ਦੀ ਅਸ਼ਲੀਲ ਨੁਮਾਇੰਦਗੀ" ਵਾਲੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰਨਾ; </font><font style="vertical-align: inherit;">ਜਾਂ ਸਾਈਟ ਦੁਆਰਾ ਕਿਸੇ ਵੀ ਇਲੈਕਟ੍ਰਾਨਿਕ ਰੂਪ ਵਿੱਚ ਪ੍ਰਦਰਸ਼ਿਤ ਜਾਂ ਪ੍ਰਸਾਰਿਤ ਜਾਂ ਪ੍ਰਸਾਰਿਤ ਕੀਤੇ ਜਾਣ ਦਾ ਕਾਰਨ, ਕੋਈ ਵੀ ਸਮੱਗਰੀ ਜੋ ਲੁਭਾਉਣੀ ਹੈ ਜਾਂ ਪ੍ਰਾਚੀਨ ਹਿੱਤਾਂ ਨੂੰ ਅਪੀਲ ਕਰਦੀ ਹੈ ਜਾਂ ਜੇ ਇਸਦਾ ਪ੍ਰਭਾਵ ਅਜਿਹੇ ਲੋਕਾਂ ਨੂੰ ਭ੍ਰਿਸ਼ਟ ਅਤੇ ਭ੍ਰਿਸ਼ਟ ਕਰਨ ਲਈ ਹੁੰਦਾ ਹੈ ਜੋ ਸੰਭਾਵਤ ਤੌਰ 'ਤੇ, ਤੱਥ ਇਹ ਹੈ ਕਿ ਸਾਈਟ ਉਹਨਾਂ ਵਿਦਿਆਰਥੀਆਂ ਦੁਆਰਾ ਵਿਦਿਅਕ ਅਤੇ ਅਕਾਦਮਿਕ ਪਿੱਛਾ ਕਰਨ ਲਈ ਹੈ ਜੋ ਅਜੇ ਵੀ ਅਜਿਹੀ ਉਮਰ ਵਿੱਚ ਸ਼ਾਮਲ ਜਾਂ ਅਜਿਹੇ ਪ੍ਰਸਾਰਣ ਵਿੱਚ ਸ਼ਾਮਲ ਸਮੱਗਰੀ ਦੀ ਯੋਗਤਾ ਨੂੰ ਸਮਝਣ ਦੇ ਯੋਗ ਨਹੀਂ ਹੋਏ ਹਨ;</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਅਪਲੋਡ ਕਰੋ, ਪੋਸਟ ਕਰੋ, ਈਮੇਲ ਕਰੋ ਜਾਂ ਕਿਸੇ ਹੋਰ ਸਮਗਰੀ ਨੂੰ ਪ੍ਰਸਾਰਿਤ ਕਰੋ ਜੋ ਗੈਰ-ਕਾਨੂੰਨੀ, ਨੁਕਸਾਨਦੇਹ, ਧਮਕੀ ਦੇਣ ਵਾਲੀ, ਅਪਮਾਨਜਨਕ, ਪਰੇਸ਼ਾਨ ਕਰਨ ਵਾਲੀ, ਕਠੋਰ, ਅਪਮਾਨਜਨਕ, ਅਸ਼ਲੀਲ, ਅਸ਼ਲੀਲ, ਅਪਮਾਨਜਨਕ, ਕਿਸੇ ਹੋਰ ਦੀ ਗੋਪਨੀਯਤਾ ਲਈ ਹਮਲਾਵਰ, ਨਫ਼ਰਤ, ਜਾਂ ਨਸਲੀ, ਨਸਲੀ ਜਾਂ ਹੋਰ ਇਤਰਾਜ਼ਯੋਗ ਹੈ; </font><font style="vertical-align: inherit;">ਜਾਂ ਦੇਸ਼ ਦੀ ਫਿਰਕੂ ਸਦਭਾਵਨਾ, ਸ਼ਾਂਤੀ ਅਤੇ ਸੁਰੱਖਿਆ ਲਈ ਖ਼ਤਰਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕਿਸੇ ਵੀ ਅਜਿਹੀ ਸਮੱਗਰੀ ਨੂੰ ਅੱਪਲੋਡ, ਪੋਸਟ, ਈਮੇਲ ਜਾਂ ਹੋਰ ਪ੍ਰਸਾਰਿਤ ਕਰੋ ਜਿਸਨੂੰ ਉਪਭੋਗਤਾ ਨੂੰ ਕਿਸੇ ਕਾਨੂੰਨ ਦੇ ਅਧੀਨ ਜਾਂ ਇਕਰਾਰਨਾਮੇ ਜਾਂ ਭਰੋਸੇਮੰਦ ਸਬੰਧਾਂ (ਜਿਵੇਂ ਕਿ ਅੰਦਰੂਨੀ ਜਾਣਕਾਰੀ, ਮਾਲਕੀ ਅਤੇ ਗੁਪਤ ਜਾਣਕਾਰੀ ਜੋ ਰੁਜ਼ਗਾਰ ਸਬੰਧਾਂ ਦੇ ਹਿੱਸੇ ਵਜੋਂ ਸਿੱਖੀ ਜਾਂ ਪ੍ਰਗਟ ਕੀਤੀ ਗਈ ਹੈ) ਦੇ ਅਧੀਨ ਸੰਚਾਰਿਤ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਨਹੀਂ ਹੈ ਜਾਂ ਗੈਰ-ਖੁਲਾਸਾ ਸਮਝੌਤਿਆਂ ਦੇ ਅਧੀਨ);</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਸੇਵਾ ਜਾਂ ਸੇਵਾ ਨਾਲ ਜੁੜੇ ਸਰਵਰਾਂ ਜਾਂ ਨੈੱਟਵਰਕਾਂ ਵਿੱਚ ਦਖਲ ਦੇਣਾ ਜਾਂ ਵਿਘਨ ਪਾਉਣਾ, ਜਾਂ ਸੇਵਾ ਨਾਲ ਜੁੜੇ ਨੈੱਟਵਰਕਾਂ ਦੀਆਂ ਕਿਸੇ ਵੀ ਲੋੜਾਂ, ਪ੍ਰਕਿਰਿਆਵਾਂ, ਨੀਤੀਆਂ ਜਾਂ ਨਿਯਮਾਂ ਦੀ ਉਲੰਘਣਾ ਕਰਨਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਜਾਣਬੁੱਝ ਕੇ ਜਾਂ ਅਣਜਾਣੇ ਵਿੱਚ ਕਿਸੇ ਵੀ ਲਾਗੂ ਸਥਾਨਕ, ਰਾਜ, ਰਾਸ਼ਟਰੀ ਜਾਂ ਅੰਤਰਰਾਸ਼ਟਰੀ ਕਾਨੂੰਨ ਦੀ ਉਲੰਘਣਾ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕੋਈ ਹੋਰ ਆਚਰਣ, ਕੰਮ ਜਾਂ ਵਿਵਹਾਰ ਜੋ ਗੈਰ-ਕਾਨੂੰਨੀ ਜਾਂ ਗੈਰ-ਕਾਨੂੰਨੀ ਹੈ; </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਜਦੋਂ ਕਿ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਆਪਣੀ ਸਾਈਟ 'ਤੇ ਅਜਿਹੇ ਆਚਰਣ ਅਤੇ ਸਮੱਗਰੀ ਦੀ ਮਨਾਹੀ ਕਰਦਾ ਹੈ, ਉਪਭੋਗਤਾ ਸਮਝਦਾ ਹੈ ਅਤੇ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ ਕਿ ਫਿਰ ਵੀ ਉਹ ਅਜਿਹੀ ਜਾਣਕਾਰੀ ਸਮੱਗਰੀ ਦੇ ਸੰਪਰਕ ਵਿੱਚ ਆ ਸਕਦੇ ਹਨ ਅਤੇ ਉਹ ਮੇਰੀ ਫਾਰਮਹਾਊਸ ਨੂੰ ਅਜਿਹੀ ਉਲੰਘਣਾ ਬਾਰੇ ਤੁਰੰਤ ਸੂਚਿਤ ਕਰਨਗੇ। </font><font style="vertical-align: inherit;">ਜੇਕਰ ਉਪਭੋਗਤਾ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਕਰਨਾ ਜਾਰੀ ਰੱਖਦਾ ਹੈ, ਤਾਂ ਉਹ ਅਜਿਹਾ ਆਪਣੇ ਜੋਖਮ ਅਤੇ ਜੋਖਮ 'ਤੇ ਕਰਨਗੇ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਸਮੱਗਰੀ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸਾਈਟ ਦੇ ਕੁਝ ਤੱਤਾਂ ਵਿੱਚ ਉਪਭੋਗਤਾਵਾਂ ਦੁਆਰਾ ਪੇਸ਼ ਕੀਤੀ ਸਮੱਗਰੀ ਸ਼ਾਮਲ ਹੋਵੇਗੀ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਅਜਿਹੀ ਸਮੱਗਰੀ ਦੇ ਲਾਗੂ ਕਾਨੂੰਨਾਂ ਦੀ ਸਮੱਗਰੀ ਅਤੇ ਸਮੱਗਰੀ, ਸ਼ੁੱਧਤਾ, ਅਨੁਕੂਲਤਾ ਲਈ ਕੋਈ ਜ਼ਿੰਮੇਵਾਰੀ ਸਵੀਕਾਰ ਨਹੀਂ ਕਰਦਾ ਹੈ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਇਸ਼ਤਿਹਾਰ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸਾਈਟ ਆਪਣੀ ਮਰਜ਼ੀ ਨਾਲ ਇਸ਼ਤਿਹਾਰ ਦਿਖਾ ਸਕਦੀ ਹੈ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ 'ਤੇ ਜਾਂ ਉਸ ਦੁਆਰਾ ਪਾਏ ਗਏ ਵਿਗਿਆਪਨਕਰਤਾਵਾਂ ਦੇ ਨਾਲ ਉਪਭੋਗਤਾਵਾਂ ਦੇ ਪੱਤਰ-ਵਿਹਾਰ ਜਾਂ ਵਪਾਰਕ ਲੈਣ-ਦੇਣ, ਜਾਂ ਉਹਨਾਂ ਦੇ ਪ੍ਰੋਮੋਸ਼ਨਾਂ ਵਿੱਚ ਭਾਗੀਦਾਰੀ, ਜਿਸ ਵਿੱਚ ਸੰਬੰਧਿਤ ਸਮਾਨ ਜਾਂ ਸੇਵਾਵਾਂ ਦਾ ਭੁਗਤਾਨ ਅਤੇ ਡਿਲਿਵਰੀ ਸ਼ਾਮਲ ਹੈ, ਅਤੇ ਅਜਿਹੇ ਸੌਦਿਆਂ ਨਾਲ ਸੰਬੰਧਿਤ ਕੋਈ ਹੋਰ ਨਿਯਮ, ਸ਼ਰਤਾਂ, ਵਾਰੰਟੀਆਂ ਜਾਂ ਪ੍ਰਤੀਨਿਧਤਾਵਾਂ, ਸਿਰਫ਼ ਉਪਭੋਗਤਾ ਅਤੇ ਅਜਿਹੇ ਵਿਗਿਆਪਨਕਰਤਾ ਦੇ ਵਿਚਕਾਰ ਹਨ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਇਸ ਗੱਲ ਨਾਲ ਸਹਿਮਤ ਹੈ ਕਿ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਅਜਿਹੇ ਕਿਸੇ ਵੀ ਸੌਦੇ ਦੇ ਨਤੀਜੇ ਵਜੋਂ ਜਾਂ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ 'ਤੇ ਅਜਿਹੇ ਇਸ਼ਤਿਹਾਰ ਦੇਣ ਵਾਲਿਆਂ ਦੀ ਮੌਜੂਦਗੀ ਦੇ ਨਤੀਜੇ ਵਜੋਂ ਹੋਏ ਕਿਸੇ ਵੀ ਤਰ੍ਹਾਂ ਦੇ ਨੁਕਸਾਨ ਜਾਂ ਨੁਕਸਾਨ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਜਾਂ ਜਵਾਬਦੇਹ ਨਹੀਂ ਹੋਵੇਗਾ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮਲਕੀਅਤ ਦੇ ਅਧਿਕਾਰ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਸਵੀਕਾਰ ਕਰਦਾ ਹੈ ਕਿ ਕਾਪੀਰਾਈਟ, ਪੇਟੈਂਟ, ਟ੍ਰੇਡਮਾਰਕ, ਉਤਪਾਦਾਂ, ਮੋਡਿਊਲਾਂ, ਸਮੱਗਰੀਆਂ ਅਤੇ ਪ੍ਰੋਗਰਾਮਾਂ ਵਿੱਚ ਵਪਾਰਕ ਭੇਦ ਸਮੇਤ ਪਰ ਇਹਨਾਂ ਤੱਕ ਹੀ ਸੀਮਿਤ ਨਾ ਹੋਣ ਵਾਲੇ ਸਾਰੇ ਬੌਧਿਕ ਸੰਪੱਤੀ ਅਧਿਕਾਰ ਹਰ ਸਮੇਂ ਕੰਪਨੀ ਦੇ ਕੋਲ ਜਾਰੀ ਰਹਿਣਗੇ। </font><font style="vertical-align: inherit;">ਵਿਦਿਆਰਥੀ/ਮਾਪਿਆਂ ਨੂੰ ਅਜਿਹੇ ਪ੍ਰੋਗਰਾਮਾਂ ਦੀ ਖਰੀਦਦਾਰੀ ਕਰਕੇ ਪ੍ਰੋਗਰਾਮਾਂ ਵਿੱਚ ਬੌਧਿਕ ਸੰਪੱਤੀ ਉੱਤੇ ਕਿਸੇ ਵੀ ਅਧਿਕਾਰ ਦਾ ਦਾਅਵਾ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਨਹੀਂ ਹੋਵੇਗਾ। </font><font style="vertical-align: inherit;">ਇਸ ਤੋਂ ਇਲਾਵਾ, ਕਿਸੇ ਵੀ ਸਥਿਤੀ ਵਿੱਚ, ਵਿਦਿਆਰਥੀ/ਮਾਪੇ ਕਾਪੀਆਂ ਬਣਾਉਣ ਦਾ ਅਧਿਕਾਰ ਪ੍ਰਾਪਤ ਨਹੀਂ ਕਰਨਗੇ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਸਵੀਕਾਰ ਕਰਦਾ ਹੈ ਕਿ ਇਸ ਧਾਰਾ ਦੀ ਉਲੰਘਣਾ ਜਾਂ ਧਮਕੀ ਦਿੱਤੀ ਗਈ ਉਲੰਘਣਾ ਦੀ ਸਥਿਤੀ ਵਿੱਚ, ਮੁਦਰਾ ਨੁਕਸਾਨ ਇੱਕ ਢੁਕਵਾਂ ਉਪਾਅ ਨਹੀਂ ਹੋ ਸਕਦਾ ਹੈ, ਇਸਲਈ, ਕੰਪਨੀ ਹੋਰ ਅਧਿਕਾਰਾਂ ਅਤੇ ਉਪਚਾਰਾਂ ਦੇ ਨਾਲ-ਨਾਲ ਵਿਦਿਆਰਥੀ/ਮਾਤਾ-ਪਿਤਾ ਨੂੰ ਇਸ ਤੋਂ ਰੋਕਣ ਲਈ ਆਦੇਸ਼ਕਾਰੀ ਰਾਹਤ ਦੀ ਹੱਕਦਾਰ ਹੋਵੇਗੀ। ਕੋਈ ਵੀ ਅਜਿਹੀ ਉਲੰਘਣਾ, ਧਮਕੀ ਜਾਂ ਅਸਲ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਅੱਗੇ ਸਵੀਕਾਰ ਕਰਦਾ ਹੈ ਅਤੇ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ ਕਿ ਸਪਾਂਸਰ ਇਸ਼ਤਿਹਾਰਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਸਮੱਗਰੀ ਅਤੇ ਸਮਗਰੀ ਜਾਂ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾਵਾਂ ਜਾਂ ਵਿਗਿਆਪਨਕਰਤਾਵਾਂ ਦੁਆਰਾ ਉਪਭੋਗਤਾ ਨੂੰ ਪੇਸ਼ ਕੀਤੀ ਗਈ ਜਾਣਕਾਰੀ ਕਾਪੀਰਾਈਟਸ, ਟ੍ਰੇਡਮਾਰਕ, ਸੇਵਾ ਚਿੰਨ੍ਹ, ਪੇਟੈਂਟ ਜਾਂ ਹੋਰ ਮਲਕੀਅਤ ਅਧਿਕਾਰਾਂ ਅਤੇ ਕਾਨੂੰਨਾਂ ਦੁਆਰਾ ਸੁਰੱਖਿਅਤ ਹੈ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਜਾਂ ਵਿਗਿਆਪਨਦਾਤਾਵਾਂ ਦੁਆਰਾ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਅਧਿਕਾਰਤ ਹੋਣ ਤੋਂ ਇਲਾਵਾ, ਉਪਭੋਗਤਾ ਪੂਰੀ ਜਾਂ ਅੰਸ਼ਕ ਤੌਰ 'ਤੇ, ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੇ ਅਧਾਰ 'ਤੇ ਸੰਸ਼ੋਧਿਤ, ਕਿਰਾਏ, ਲੀਜ਼, ਲੋਨ, ਵੇਚਣ, ਵੰਡਣ ਜਾਂ ਡੈਰੀਵੇਟਿਵ ਕੰਮਾਂ ਨੂੰ ਨਾ ਬਣਾਉਣ ਲਈ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਵਾਰੰਟੀਆਂ ਦਾ ਬੇਦਾਅਵਾ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਸਮਝਦਾ ਹੈ ਅਤੇ ਸਹਿਮਤ ਹੈ ਕਿ: - ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਉਪਭੋਗਤਾ ਦੇ ਇਕੱਲੇ ਜੋਖਮ 'ਤੇ ਹੈ। </font><font style="vertical-align: inherit;">ਸੇਵਾ "ਜਿਵੇਂ ਹੈ" ਅਤੇ "ਜਿਵੇਂ ਉਪਲਬਧ ਹੈ" ਦੇ ਆਧਾਰ 'ਤੇ ਪ੍ਰਦਾਨ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਕਿਸੇ ਵੀ ਕਿਸਮ ਦੀਆਂ ਸਾਰੀਆਂ ਵਾਰੰਟੀਆਂ ਨੂੰ ਅਸਵੀਕਾਰ ਕਰਦਾ ਹੈ, ਭਾਵੇਂ ਸਪੱਸ਼ਟ ਜਾਂ ਅਪ੍ਰਤੱਖ, ਜਿਸ ਵਿੱਚ ਵਪਾਰਕਤਾ, ਕਿਸੇ ਖਾਸ ਉਦੇਸ਼ ਲਈ ਤੰਦਰੁਸਤੀ ਅਤੇ ਗੈਰ-ਉਲੰਘਣ ਦੀ ਅਪ੍ਰਤੱਖ ਵਾਰੰਟੀਆਂ ਸ਼ਾਮਲ ਹਨ, ਪਰ ਇਹ ਸੀਮਿਤ ਨਹੀਂ ਹੈ।</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਕੋਈ ਵਾਰੰਟੀ ਨਹੀਂ ਦਿੰਦਾ ਹੈ ਕਿ (i) ਸੇਵਾ ਉਪਭੋਗਤਾ ਦੀਆਂ ਲੋੜਾਂ ਨੂੰ ਪੂਰਾ ਕਰੇਗੀ, (ii) ਸੇਵਾ ਨਿਰਵਿਘਨ, ਸਮੇਂ ਸਿਰ, ਸੁਰੱਖਿਅਤ, ਜਾਂ ਗਲਤੀ-ਰਹਿਤ ਹੋਵੇਗੀ, (iii) ਨਤੀਜੇ ਜੋ ਕਿ ਵਰਤੋਂ ਤੋਂ ਪ੍ਰਾਪਤ ਕੀਤੇ ਜਾ ਸਕਦੇ ਹਨ। ਸੇਵਾ ਸਹੀ ਜਾਂ ਭਰੋਸੇਮੰਦ ਹੋਵੇਗੀ, (iv) ਕਿਸੇ ਵੀ ਉਤਪਾਦ, ਸੇਵਾਵਾਂ, ਜਾਣਕਾਰੀ, ਜਾਂ ਸੇਵਾ ਦੁਆਰਾ ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਖਰੀਦੀ ਜਾਂ ਪ੍ਰਾਪਤ ਕੀਤੀ ਗਈ ਹੋਰ ਸਮੱਗਰੀ ਦੀ ਗੁਣਵੱਤਾ ਉਪਭੋਗਤਾ ਦੀਆਂ ਉਮੀਦਾਂ ਨੂੰ ਪੂਰਾ ਕਰੇਗੀ, ਅਤੇ (v) ਸੌਫਟਵੇਅਰ ਵਿੱਚ ਕਿਸੇ ਵੀ ਤਰੁੱਟੀ ਨੂੰ ਠੀਕ ਕੀਤਾ ਜਾਵੇਗਾ . </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਕੋਈ ਵੀ ਸਮੱਗਰੀ ਡਾਊਨਲੋਡ ਕੀਤੀ ਜਾਂ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਰਾਹੀਂ ਪ੍ਰਾਪਤ ਕੀਤੀ ਗਈ ਹੈ, ਉਪਭੋਗਤਾ ਦੇ ਆਪਣੇ ਵਿਵੇਕ ਅਤੇ ਜੋਖਮ 'ਤੇ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਅਤੇ ਉਹ ਉਪਭੋਗਤਾ ਉਪਭੋਗਤਾ ਦੇ ਕੰਪਿਊਟਰ ਸਿਸਟਮ ਨੂੰ ਹੋਣ ਵਾਲੇ ਕਿਸੇ ਵੀ ਨੁਕਸਾਨ ਜਾਂ ਅਜਿਹੀ ਸਮੱਗਰੀ ਦੇ ਡਾਉਨਲੋਡ ਦੇ ਨਤੀਜੇ ਵਜੋਂ ਡੇਟਾ ਦੇ ਨੁਕਸਾਨ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਜ਼ਿੰਮੇਵਾਰ ਹੋਵੇਗਾ।</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਕੋਈ ਵੀ ਸਲਾਹ ਜਾਂ ਜਾਣਕਾਰੀ, ਭਾਵੇਂ ਮੌਖਿਕ ਜਾਂ ਲਿਖਤੀ, ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਤੋਂ ਜਾਂ ਸੇਵਾ ਦੁਆਰਾ ਜਾਂ ਸੇਵਾ ਤੋਂ ਪ੍ਰਾਪਤ ਕੀਤੀ ਗਈ ਕੋਈ ਵੀ ਵਾਰੰਟੀ ਨਹੀਂ ਬਣਾਏਗੀ, ਜੋ ਕਿ ToS ਵਿੱਚ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਨਹੀਂ ਦੱਸੀ ਗਈ ਹੈ।
</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਦੇਣਦਾਰੀ ਦੀ ਸੀਮਾ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਕਿਸੇ ਵੀ ਹਾਲਤ ਵਿੱਚ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਨਾਲ ਜਾਂ ਇਸ ਦੇ ਸਬੰਧ ਵਿੱਚ ਹੋਣ ਵਾਲੇ ਕਿਸੇ ਵੀ ਅਸਿੱਧੇ, ਇਤਫਾਕਨ, ਨਤੀਜੇ ਵਜੋਂ, ਵਿਸ਼ੇਸ਼ ਜਾਂ ਮਿਸਾਲੀ ਨੁਕਸਾਨ ਲਈ ਉਪਭੋਗਤਾ ਲਈ ਜਵਾਬਦੇਹ ਨਹੀਂ ਹੋਵੇਗਾ, ਭਾਵੇਂ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਨੂੰ ਅਜਿਹੀ ਸੰਭਾਵਨਾ ਬਾਰੇ ਸਲਾਹ ਦਿੱਤੀ ਗਈ ਹੈ ਜਾਂ ਨਹੀਂ। ਨੁਕਸਾਨ </font><font style="vertical-align: inherit;">ਦੇਣਦਾਰੀ ਦੀ ਅਜਿਹੀ ਸੀਮਾ ਲਾਗੂ ਹੋਵੇਗੀ (i) ਕੀ ਨੁਕਸਾਨ ਮੀਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਜਾਂ ਦੁਰਵਰਤੋਂ ਅਤੇ ਇਸ 'ਤੇ ਨਿਰਭਰਤਾ, ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੀ ਵਰਤੋਂ ਕਰਨ ਦੀ ਅਸਮਰੱਥਾ, ਜਾਂ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੇ ਰੁਕਾਵਟ, ਮੁਅੱਤਲ ਜਾਂ ਸਮਾਪਤੀ ਤੋਂ ਪੈਦਾ ਹੁੰਦਾ ਹੈ ( ਤੀਜੇ ਪੱਖਾਂ ਦੁਆਰਾ ਕੀਤੇ ਗਏ ਅਜਿਹੇ ਨੁਕਸਾਨਾਂ ਸਮੇਤ), ਅਤੇ (ii) ਕਿਸੇ ਵੀ ਸੀਮਤ ਉਪਾਅ ਦੇ ਜ਼ਰੂਰੀ ਉਦੇਸ਼ ਦੀ ਅਸਫਲਤਾ ਦੇ ਬਾਵਜੂਦ ਅਤੇ ਕਾਨੂੰਨ ਦੁਆਰਾ ਆਗਿਆ ਦਿੱਤੀ ਗਈ ਪੂਰੀ ਹੱਦ ਤੱਕ। </font><font style="vertical-align: inherit;">ਕਿਸੇ ਵੀ ਹਾਲਤ ਵਿੱਚ ਮੀਰਾ ਫਾਰਮਹਾਊਸ ਇੱਕ ਹਜ਼ਾਰ ਰੁਪਏ ਤੋਂ ਵੱਧ ਦੀ ਕਿਸੇ ਵੀ ਰਕਮ ਲਈ ਉਪਭੋਗਤਾ ਲਈ ਜਵਾਬਦੇਹ ਨਹੀਂ ਹੋਵੇਗਾ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੁਆਵਜ਼ਾ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਮੇਰਾ ਫਾਰਮਹਾਊਸ, ਅਤੇ ਇਸ ਦੀਆਂ ਸਹਾਇਕ ਕੰਪਨੀਆਂ, ਸਹਿਯੋਗੀਆਂ, ਅਫਸਰਾਂ, ਏਜੰਟਾਂ, ਸਹਿ-ਬ੍ਰਾਂਡਰਾਂ ਜਾਂ ਹੋਰ ਭਾਈਵਾਲਾਂ, ਅਤੇ ਕਰਮਚਾਰੀਆਂ ਨੂੰ ਮੁਆਵਜ਼ਾ ਦੇਣ ਅਤੇ ਰੱਖਣ ਲਈ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ, ਕਿਸੇ ਵੀ ਦਾਅਵੇ ਜਾਂ ਮੰਗ ਤੋਂ ਨੁਕਸਾਨ ਰਹਿਤ, ਵਾਜਬ ਅਟਾਰਨੀ ਫੀਸਾਂ ਸਮੇਤ, ਕਿਸੇ ਤੀਜੀ ਧਿਰ ਦੁਆਰਾ ਕੀਤੀ ਗਈ ਜਾਂ ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਸੇਵਾ ਦੁਆਰਾ ਸਪੁਰਦ, ਪੋਸਟ ਜਾਂ ਸੰਚਾਰਿਤ ਸਮੱਗਰੀ, ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਸੇਵਾ ਦੀ ਵਰਤੋਂ, ਸੇਵਾ ਨਾਲ ਉਪਭੋਗਤਾ ਦੇ ਕਨੈਕਸ਼ਨ, ਉਪਭੋਗਤਾ ਦੁਆਰਾ ToS ਦੀ ਉਲੰਘਣਾ, ਜਾਂ ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਕਿਸੇ ਹੋਰ ਦੇ ਅਧਿਕਾਰਾਂ ਦੀ ਉਲੰਘਣਾ ਤੋਂ ਪੈਦਾ ਹੋਈ ਸਮੱਗਰੀ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸੇਵਾ ਦੀ ਕੋਈ ਮੁੜ ਵਿਕਰੀ ਨਹੀਂ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਕਿਸੇ ਵੀ ਵਪਾਰਕ ਉਦੇਸ਼ਾਂ, ਸੇਵਾ ਦੇ ਕਿਸੇ ਵੀ ਹਿੱਸੇ, ਸੇਵਾ ਦੀ ਵਰਤੋਂ, ਜਾਂ ਸੇਵਾ ਤੱਕ ਪਹੁੰਚ ਲਈ ਦੁਬਾਰਾ ਪੈਦਾ ਕਰਨ, ਡੁਪਲੀਕੇਟ, ਕਾਪੀ, ਵੇਚਣ, ਦੁਬਾਰਾ ਵੇਚਣ ਜਾਂ ਸ਼ੋਸ਼ਣ ਨਾ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹੁੰਦਾ ਹੈ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸੇਵਾ ਵਿੱਚ ਸੋਧ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਕਿਸੇ ਵੀ ਸਮੇਂ ਅਤੇ ਸਮੇਂ-ਸਮੇਂ 'ਤੇ, ਸੇਵਾ (ਜਾਂ ਇਸਦੇ ਕਿਸੇ ਵੀ ਹਿੱਸੇ) ਨੂੰ ਨੋਟਿਸ ਦੇ ਨਾਲ ਜਾਂ ਬਿਨਾਂ, ਅਸਥਾਈ ਤੌਰ 'ਤੇ ਜਾਂ ਸਥਾਈ ਤੌਰ 'ਤੇ ਸੋਧਣ ਜਾਂ ਬੰਦ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਰੱਖਦਾ ਹੈ। </font><font style="vertical-align: inherit;">ਉਪਭੋਗਤਾ ਸਹਿਮਤ ਹੈ ਕਿ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਸੇਵਾ ਦੇ ਕਿਸੇ ਵੀ ਸੋਧ, ਮੁਅੱਤਲੀ ਜਾਂ ਬੰਦ ਕਰਨ ਲਈ ਉਪਭੋਗਤਾ ਜਾਂ ਕਿਸੇ ਤੀਜੀ ਧਿਰ ਲਈ ਜਵਾਬਦੇਹ ਨਹੀਂ ਹੋਵੇਗਾ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਨੋਟਿਸ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਨੂੰ ਨੋਟਿਸ ਈਮੇਲ ਜਾਂ ਨਿਯਮਤ ਮੇਲ ਦੁਆਰਾ ਕੀਤੇ ਜਾ ਸਕਦੇ ਹਨ। </font><font style="vertical-align: inherit;">ਸਾਈਟ ਦੀ ਸੇਵਾ ਆਮ ਤੌਰ 'ਤੇ ਸੇਵਾ 'ਤੇ ਉਪਭੋਗਤਾ ਨੂੰ ਨੋਟਿਸਾਂ ਜਾਂ ਨੋਟਿਸਾਂ ਦੇ ਲਿੰਕ ਪ੍ਰਦਰਸ਼ਿਤ ਕਰਕੇ TOS ਜਾਂ ਹੋਰ ਮਾਮਲਿਆਂ ਵਿੱਚ ਤਬਦੀਲੀਆਂ ਦੇ ਨੋਟਿਸ ਵੀ ਪ੍ਰਦਾਨ ਕਰ ਸਕਦੀ ਹੈ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਲੰਘਣਾਵਾਂ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਸਮਝੌਤੇ ਦੇ ਨਿਯਮਾਂ ਅਤੇ ਸ਼ਰਤਾਂ ਦੀ ਕਿਸੇ ਵੀ ਉਲੰਘਣਾ ਦੀ ਰਿਪੋਰਟ info@merafarmhouse.com 'ਤੇ ਕਰੋ</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਅਪ੍ਰਤਿਆਸ਼ਿਤ ਘਟਨਾ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਉਹਨਾਂ ਮਾਮਲਿਆਂ ਲਈ ਉਪਭੋਗਤਾ ਲਈ ਕੋਈ ਜਵਾਬਦੇਹੀ ਨਹੀਂ ਹੋਵੇਗਾ ਜਿੱਥੇ ਇਸਦਾ ਕੋਈ ਨਿਯੰਤਰਣ ਨਹੀਂ ਹੈ ਜਾਂ ਜੋ ਇਸਦੇ ਨਿਯੰਤਰਣ ਤੋਂ ਬਾਹਰ ਹਨ ਅਤੇ ਇਸ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਆਉਂਦੇ ਹਨ।
</font></font><br><br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਪੂਰਾ ਇਕਰਾਰਨਾਮਾ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਸੇਵਾ ਦੀਆਂ ਇਹ ਸ਼ਰਤਾਂ ਇਸ ਦੇ ਵਿਸ਼ੇ ਦੇ ਸਬੰਧ ਵਿੱਚ ਧਿਰਾਂ ਵਿਚਕਾਰ ਪੂਰੇ ਸਮਝੌਤੇ ਦਾ ਗਠਨ ਕਰਦੀਆਂ ਹਨ ਅਤੇ ਅਜਿਹੇ ਵਿਸ਼ੇ ਦੇ ਸੰਬੰਧ ਵਿੱਚ ਲਿਖਤੀ ਜਾਂ ਜ਼ੁਬਾਨੀ, ਸਾਰੀਆਂ ਪੁਰਾਣੀਆਂ ਜਾਂ ਸਮਕਾਲੀ ਸਮਝਾਂ ਜਾਂ ਸਮਝੌਤਿਆਂ ਨੂੰ ਬਦਲਦੀਆਂ ਹਨ ਅਤੇ ਬਦਲਦੀਆਂ ਹਨ।</font></font></p>
<br><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਗੋਪਨੀਯਤਾ ਨੀਤੀ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਉਪਭੋਗਤਾ ਸਹਿਮਤੀ ਦਿੰਦਾ ਹੈ ਕਿ ਕੰਪਨੀ ਦੇ ਉਤਪਾਦਾਂ, ਪ੍ਰੋਗਰਾਮਾਂ ਜਾਂ ਕਿਸੇ ਹੋਰ ਸੇਵਾਵਾਂ ਦੀ ਗਾਹਕੀ/ਵਰਤੋਂ ਕਰਕੇ, ਇਹ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਕੰਪਨੀ ਨੂੰ ਸਿੱਖਿਆ ਸ਼ਾਸਤਰ, ਸਿੱਖਣ ਦੇ ਨਤੀਜਿਆਂ, ਭਵਿੱਖਬਾਣੀ ਸਿੱਖਣ ਅਤੇ ਸਟੋਰ ਕਰਨ, ਵਰਤੋਂ, ਵਿਸ਼ਲੇਸ਼ਣ, ਵੰਡਣ ਜਾਂ ਕਿਸੇ ਹੋਰ ਤਰੀਕੇ ਨਾਲ ਨਜਿੱਠਣ ਦੀ ਇਜਾਜ਼ਤ ਦਿੰਦਾ ਹੈ। , ਜਿਵੇਂ ਕਿ ਕੰਪਨੀ ਉਚਿਤ ਸਮਝਦੀ ਹੈ, ਕੰਪਨੀ ਦੁਆਰਾ ਸਿੱਖਣ, ਅਭਿਆਸ ਅਤੇ ਪਰੀਖਣ ਦੀ ਵਿਲੱਖਣ ਸਿੱਖਿਆ ਅਤੇ ਕੰਪਨੀ ਦੇ ਉਤਪਾਦਾਂ, ਪ੍ਰੋਗਰਾਮਾਂ ਜਾਂ ਕਿਸੇ ਹੋਰ ਸੇਵਾਵਾਂ ਦੀ ਕੰਪਨੀ, ਇਸਦੇ ਸਹਿਯੋਗੀਆਂ ਜਾਂ ਕਿਸੇ ਤੀਜੇ ਦੇ ਤੌਰ 'ਤੇ ਗਾਹਕ ਦੁਆਰਾ ਵਰਤੋਂ ਤੋਂ ਪ੍ਰਾਪਤ ਕੀਤੀ ਜਾਣਕਾਰੀ/ਡਾਟੇ ਤੋਂ। ਪਾਰਟੀ ਜਿਵੇਂ ਕਿ ਕੰਪਨੀ ਅਧਿਕਾਰਤ ਕਰ ਸਕਦੀ ਹੈ।
</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਲਈ ਉਪਭੋਗਤਾ ਦੀ ਗੋਪਨੀਯਤਾ ਬਹੁਤ ਮਹੱਤਵਪੂਰਨ ਹੈ। </font><font style="vertical-align: inherit;">ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਦੇ ਕੁਝ ਬੁਨਿਆਦੀ ਸਿਧਾਂਤ ਹਨ: - ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਆਪਣੇ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਆਰਡਰ ਦੇਣ ਵੇਲੇ ਵੱਖ-ਵੱਖ ਨਿੱਜੀ ਡੇਟਾ ਦੀ ਸਪਲਾਈ ਕਰਨ ਲਈ ਕਹਿੰਦਾ ਹੈ, ਜਿਵੇਂ ਕਿ ਨਾਮ, ਪਤਾ, ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਦੀ ਜਾਣਕਾਰੀ, ਅਤੇ ਵੈਧ ਈ-ਮੇਲ ਆਈ.ਡੀ.</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਇਸ ਡੇਟਾ ਦੀ ਵਰਤੋਂ ਸਿਰਫ਼ ਆਰਡਰ ਭਰਨ ਜਾਂ ਆਰਡਰ ਦੀ ਸਥਿਤੀ ਬਾਰੇ ਉਪਭੋਗਤਾ ਨਾਲ ਸੰਚਾਰ ਕਰਨ ਦੇ ਉਦੇਸ਼ ਲਈ ਕਰਦਾ ਹੈ। </font><font style="vertical-align: inherit;">- ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਇਸ ਗਾਹਕ ਜਾਣਕਾਰੀ ਨੂੰ ਨਿੱਜੀ ਅਤੇ ਗੁਪਤ ਮੰਨਦਾ ਹੈ, ਅਤੇ ਇਹ ਇਸ ਜਾਣਕਾਰੀ ਨੂੰ ਹੋਰ ਵਿਅਕਤੀਆਂ ਜਾਂ ਸੰਸਥਾਵਾਂ ਨੂੰ ਉਦੋਂ ਤੱਕ ਨਹੀਂ ਦੱਸੇਗਾ ਜਦੋਂ ਤੱਕ ਕਨੂੰਨ ਦੁਆਰਾ ਲੋੜੀਂਦਾ ਨਾ ਹੋਵੇ। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਜੇਕਰ ਉਪਭੋਗਤਾ ਮਹਿਸੂਸ ਕਰਦਾ ਹੈ ਕਿ ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਨੇ ਗੋਪਨੀਯਤਾ 'ਤੇ ਇਸ ਬਿਆਨ ਦੀ ਕਿਸੇ ਵੀ ਤਰ੍ਹਾਂ ਉਲੰਘਣਾ ਕੀਤੀ ਹੈ, ਤਾਂ ਕਿਰਪਾ ਕਰਕੇ Mera Farmhouse ਨੂੰ contact@Mera Farmhouse.work 'ਤੇ ਸੰਪਰਕ ਕਰੋ ਤਾਂ ਜੋ ਅਸੀਂ ਇਸ ਮੁੱਦੇ ਨੂੰ ਹੱਲ ਕਰ ਸਕੀਏ।</font></font><br>
<br></p><h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਰਿਫੰਡ, ਰੱਦ ਕਰਨ ਅਤੇ ਪੈਕ ਦੀ ਮਿਆਦ ਪੁੱਗਣ ਦੀ ਨੀਤੀ</font></font></h5><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਇੱਕ ਵਾਰ ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਗਾਹਕੀ ਲਈ Mera Farmhouse.com 'ਤੇ ਇੱਕ ਲੈਣ-ਦੇਣ ਨੂੰ ਪੂਰਾ ਕਰਨ ਤੋਂ ਬਾਅਦ ਕੋਈ ਰਿਫੰਡ ਜਾਂ ਰੱਦ ਕਰਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ। </font><font style="vertical-align: inherit;">(ਸਿਰਫ਼ Mera Farmhouse.com ਰਾਹੀਂ ਕੀਤੀਆਂ ਖਰੀਦਾਂ ਲਈ ਵੈਧ)। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਤੁਹਾਡਾ ਗਾਹਕੀ ਪੈਕੇਜ ਸਮਾਪਤ ਹੋਣ ਤੱਕ ਜਾਰੀ ਰਹੇਗਾ। </font><font style="vertical-align: inherit;">ਜਦੋਂ ਤੱਕ ਤੁਸੀਂ ਆਪਣੇ ਭੁਗਤਾਨ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੀ ਗਾਹਕੀ ਨੂੰ ਰੱਦ ਨਹੀਂ ਕਰਦੇ, ਤੁਸੀਂ ਸਾਨੂੰ ਆਪਣੀ ਭੁਗਤਾਨ ਵਿਧੀ ਤੋਂ ਅਗਲੇ ਬਿਲਿੰਗ ਚੱਕਰ ਲਈ ਪੈਕੇਜ ਦੀ ਰਕਮ ਚਾਰਜ ਕਰਨ ਲਈ ਅਧਿਕਾਰਤ ਕਰਦੇ ਹੋ। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਸਾਇਨਅਪ ਦੇ ਦਿਨ ਤੋਂ ਤੁਹਾਨੂੰ 7-ਦਿਨ ਦੀ ਮੁਫਤ ਅਜ਼ਮਾਇਸ਼ ਮਿਲੇਗੀ। </font><font style="vertical-align: inherit;">ਤੁਸੀਂ ਸਮੱਗਰੀ ਨੂੰ ਚੰਗੀ ਤਰ੍ਹਾਂ ਐਕਸੈਸ ਕਰ ਸਕਦੇ ਹੋ। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਤੁਸੀਂ ਕਿਸੇ ਵੀ ਸਮੇਂ ਆਪਣੀ ਗਾਹਕੀ ਨੂੰ ਰੱਦ ਕਰ ਸਕਦੇ ਹੋ, ਅਤੇ ਤੁਹਾਡੀ ਭੁਗਤਾਨ ਦੀ ਮਿਤੀ ਦੇ ਅੰਤ ਤੱਕ ਪੈਕੇਜ ਤੱਕ ਤੁਹਾਡੀ ਪਹੁੰਚ ਜਾਰੀ ਰਹੇਗੀ। </font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
- ਇੱਕ ਵਾਰ ਜਦੋਂ ਤੁਸੀਂ ਆਪਣੀ ਗਾਹਕੀ ਰੱਦ ਕਰ ਦਿੰਦੇ ਹੋ, ਤਾਂ ਪੈਕੇਜ ਦੀ ਰਕਮ ਵਾਪਸ ਨਹੀਂ ਕੀਤੀ ਜਾਵੇਗੀ।</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਮੇਰਾ ਫਾਰਮਹਾਊਸ ਵਿਖੇ, ਖਰੀਦੇ ਜਾਣ ਸਮੇਂ ਸੁਝਾਏ ਗਏ ਵੈਧਤਾ ਅਨੁਸਾਰ ਪੈਕ ਦੀ ਮਿਆਦ ਖਤਮ ਹੋ ਜਾਂਦੀ ਹੈ। </font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ਗਾਹਕੀ ਦੀ ਕੀਮਤ ਤੁਹਾਨੂੰ ਸਾਈਨਅਪ ਪੰਨਿਆਂ 'ਤੇ ਜਾਂ ਨਹੀਂ ਤਾਂ ਸਾਈਨਅਪ ਪ੍ਰਕਿਰਿਆ ਦੌਰਾਨ ਸਪੱਸ਼ਟ ਕਰ ਦਿੱਤੀ ਜਾਵੇਗੀ ਅਤੇ ਸਮੇਂ-ਸਮੇਂ 'ਤੇ ਵੱਖ-ਵੱਖ ਹੋ ਸਕਦੀ ਹੈ। </font><font style="vertical-align: inherit;">ਤੁਸੀਂ ਆਪਣੇ ਸਾਈਨ ਅੱਪ ਦੇ ਸਮੇਂ ਤੁਹਾਨੂੰ ਸੂਚਿਤ ਕੀਤੀਆਂ ਦਰਾਂ 'ਤੇ ਭੁਗਤਾਨ ਕਰਨ ਲਈ ਸਹਿਮਤ ਹੋ। </font><font style="vertical-align: inherit;">ਸਾਡੀ ਐਪ 'ਤੇ ਪ੍ਰੀਮੀਅਮ ਸਮੱਗਰੀ ਲਈ ਸਾਈਨ ਅੱਪ ਕਰੋ ਆਮ ਤੌਰ 'ਤੇ ਇੱਕ ਸਾਲ ਲਈ ਹੁੰਦਾ ਹੈ। </font><font style="vertical-align: inherit;">ਅਸੀਂ, ਹਾਲਾਂਕਿ, ਮਹੀਨਾਵਾਰ ਭੁਗਤਾਨ ਵਿਕਲਪਾਂ ਦੀ ਪੇਸ਼ਕਸ਼ ਕਰਨ ਦੀ ਚੋਣ ਕਰ ਸਕਦੇ ਹਾਂ। </font><font style="vertical-align: inherit;">ਜੇਕਰ ਤੁਸੀਂ ਮਹੀਨਾਵਾਰ ਭੁਗਤਾਨ ਕਰਨਾ ਚੁਣਦੇ ਹੋ, ਤਾਂ ਤੁਹਾਡੀ ਗਾਹਕੀ ਉਦੋਂ ਤੱਕ ਜਾਰੀ ਰਹੇਗੀ ਜਦੋਂ ਤੱਕ ਤੁਸੀਂ ਸਾਨੂੰ ਇਹ ਨਹੀਂ ਦੱਸਦੇ ਕਿ ਤੁਸੀਂ ਹੁਣ ਇਸਨੂੰ ਪ੍ਰਾਪਤ ਨਹੀਂ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ, ਇਸ ਸਥਿਤੀ ਵਿੱਚ ਤੁਸੀਂ ਮਹੀਨਾਵਾਰ ਰਕਮਾਂ ਦਾ ਭੁਗਤਾਨ ਕਰਨਾ ਬੰਦ ਕਰ ਦਿਓਗੇ।</font></font><br><br>
                        </p>
                        
                        </div>

                        
                    </div>
                </div>
                
            </div>
        </div>
    </section>
    <!-- End blog_wrap -->
    <?php get_footer('custom-bi'); ?>